//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace БИПиТ5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string[][] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string[][]> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Clients", ReplyAction="http://tempuri.org/IService1/ClientsResponse")]
        System.Collections.Generic.Dictionary<int, string> Clients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Clients", ReplyAction="http://tempuri.org/IService1/ClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> ClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Services", ReplyAction="http://tempuri.org/IService1/ServicesResponse")]
        System.Collections.Generic.Dictionary<int, string> Services();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Services", ReplyAction="http://tempuri.org/IService1/ServicesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> ServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewRec", ReplyAction="http://tempuri.org/IService1/NewRecResponse")]
        void NewRec(int IdC, int IdS, int Time, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewRec", ReplyAction="http://tempuri.org/IService1/NewRecResponse")]
        System.Threading.Tasks.Task NewRecAsync(int IdC, int IdS, int Time, System.DateTime Date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : БИПиТ5.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<БИПиТ5.ServiceReference1.IService1>, БИПиТ5.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[][] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string[][]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, string> Clients() {
            return base.Channel.Clients();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> ClientsAsync() {
            return base.Channel.ClientsAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, string> Services() {
            return base.Channel.Services();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> ServicesAsync() {
            return base.Channel.ServicesAsync();
        }
        
        public void NewRec(int IdC, int IdS, int Time, System.DateTime Date) {
            base.Channel.NewRec(IdC, IdS, Time, Date);
        }
        
        public System.Threading.Tasks.Task NewRecAsync(int IdC, int IdS, int Time, System.DateTime Date) {
            return base.Channel.NewRecAsync(IdC, IdS, Time, Date);
        }
    }
}
